### ISSUE TITLE
(Feature request) "Pause" plugin, so edits can be made

### ISSUE THREAD

**Issue by TacticalSauce** [al3xw/force-read-mode#1]
Currently, trying to switch to edit mode will result in the plugin immediately switching back to read mode. If an edit needs to be made, an option to toggle the plugin on/off (perhaps in command palette) would be useful.

**Comment by al3xw** [comment]
Hey @TacticalSauce ,
thanks for sharing your idea!
Totally get how a quick toggle for the plugin would make life easier when edits are needed.
I’ll see if I can get something up this weekend or early next week.
Will keep you posted here when I make progress!

**Comment by TacticalSauce** [comment]
Thanks @al3xw and thanks for taking the time to make/share the plugin, very useful!

**Comment by al3xw** [comment]
@TacticalSauce I've implemented your requested feature in this commit a417554. The new release 1.0.3 includes your feature.
Thanks again for your suggestion!
Will close this issue for now.
